service:
  name: weather-serverless

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

resources:
  Resources:
    WeatherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WeatherTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  getWeather:
    handler: src/handlers/getWeather.handler
    events:
      - http:
          method: GET
          path: /getWeather
          request:
            parameters:
              querystrings:
                zip: true
        